# Generated by Django 4.2.30 on 2026-05-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('category', models.CharField(choices=[('suv', 'SUV / Crossover'), ('sedan', 'Sedan'), ('luxury', 'Luxury'), ('sport', 'Sports Car'), ('pickup', 'Pickup / Truck'), ('van', 'Van / Minibus')], max_length=100)),
                ('fuel', models.CharField(default='Petrol', max_length=50)),
                ('transmission', models.CharField(default='Automatic', max_length=50)),
                ('mileage', models.IntegerField(default=0)),
                ('colour', models.CharField(blank=True, max_length=50)),
                ('price', models.BigIntegerField()),
                ('price_note', models.CharField(blank=True, max_length=100)),
                ('badge', models.CharField(blank=True, choices=[('new', 'New Arrival'), ('hot', 'Hot'), ('deal', 'Best Deal'), ('', 'No Badge')], max_length=10)),
                ('featured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold')], default='available', max_length=20)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('wa_message', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
                'ordering': ['-featured', '-created_at'],
            },
        ),
    ]
