services:
  - type: web
    name: elizade-motors
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn elizade.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true